### Login (retorna accessToken e refreshToken)
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "joao@email.com",
  "password": "123456"
}

> {%
    client.global.set("token", response.body.accessToken);
    client.global.set("refreshToken", response.body.refreshToken);
%}



### Refresh token (gera novo accessToken)
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

> {%
    client.global.set("token", response.body.accessToken);
%}



### Logout (revoga o refreshToken)
POST {{baseUrl}}/auth/logout
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

### Refresh após logout (deve retornar erro 4xx)
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}
