ALTER TABLE tb_users
ALTER COLUMN name TYPE VARCHAR(150);

ALTER TABLE tb_users
ALTER COLUMN email TYPE VARCHAR(254);

ALTER TABLE tb_users
ALTER COLUMN password TYPE VARCHAR(60);

ALTER TABLE tb_refresh_tokens
ALTER COLUMN token TYPE VARCHAR(64);
